# Generated by Django 2.0.6 on 2019-04-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apiKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('apiToken', models.CharField(max_length=100)),
                ('apiRefreshToken', models.CharField(max_length=100)),
            ],
        ),
    ]
