# Generated by Django 2.0.6 on 2019-03-12 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersong',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='usersong',
            name='title',
        ),
    ]
