# Generated by Django 2.0.6 on 2019-03-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_usersong_mimetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersong',
            name='originalname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
