# Generated by Django 2.0.6 on 2019-03-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_usersong_originalname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersong',
            name='sn',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
