# Generated by Django 2.0.6 on 2019-03-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190313_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersong',
            name='timesplayed',
            field=models.IntegerField(default=0),
        ),
    ]
